export const QUERY_EXECUTE_REQUESTED = 'QUERY_EXECUTE_REQUESTED';
export const QUERY_EXECUTE_REQUEST_SUCCESS = 'QUERY_EXECUTE_REQUEST_SUCCESS';
export const QUERY_EXECUTE_REQUEST_FAILED = 'QUERY_EXECUTE_REQUEST_FAILED';
