export const CLUSTER_FETCH_REQUESTED = 'CLUSTER_FETCH_REQUESTED';
export const CLUSTER_FETCH_SUCCESS = 'CLUSTER_FETCH_SUCCESS';
export const CLUSTER_FETCH_FAILED = 'CLUSTER_FETCH_FAILED';
export const CLUSTER_FETCH_ALL_NODES_REQUESTED = 'CLUSTER_FETCH_ALL_NODES_REQUESTED';
export const CLUSTER_FETCH_ALL_NODES_SUCCESS = 'CLUSTER_FETCH_ALL_NODES_SUCCESS';
export const CLUSTER_FETCH_ALL_NODES_FAILED = 'CLUSTER_FETCH_ALL_NODES_FAILED';
